# file: postgresql/tasks/extensions.yml

- import_tasks: extensions/contrib.yml
  when: postgresql_ext_install_contrib
- import_tasks: extensions/dev_headers.yml
  when: postgresql_ext_install_dev_headers
- import_tasks: extensions/postgis.yml
  when: postgresql_ext_install_postgis
- import_tasks: extensions/apt_2ndquadrant_repositories.yml
  when: ansible_pkg_mgr == "apt" and ( postgresql_ext_install_repmgr or postgresql_ext_install_barman )
- import_tasks: extensions/repmgr.yml
  when: postgresql_ext_install_repmgr and ansible_service_mgr == 'systemd'
- import_tasks: extensions/barman.yml
  when: ansible_pkg_mgr == "apt" and postgresql_ext_install_barman
