---
# vim: set syntax=yaml expandtab shiftwidth=2 tabstop=2 softtabstop=2 autoindent smartindent:
# file: postgresql/handlers/main.yml

- name: reload postgresql
  include_tasks: "{{ role_path }}/handlers/reload.yml"

- name: restart postgresql
  include_tasks: "{{ role_path }}/handlers/restart.yml"

 - name: restart repmgr
   service:
     name: "repmgr{{postgresql_version}}"
     state: restarted
     enabled: yes
